### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mzch** [ToolReaz/fyler#1]
When running `npm run build`, the following error occurred:

```nodejs
> fyler@0.0.1-alpha build
> next build

Loaded env from /srv/fyler/fyler/.env
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[    ] info  - Generating static pages (0/4)
Error occurred prerendering page "/register". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot read property 'indexOf' of null
    at /srv/fyler/fyler/node_modules/rc-menu/lib/MenuItem.js:254:30
    at new Connect(MenuItem) (/srv/fyler/fyler/node_modules/mini-store/cjs/connect.js:64:33)
    at d (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
    at bb (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/srv/fyler/fyler/node_modules/next/dist/next-server/server/render.js:53:851)
    at Function.getInitialProps (/srv/fyler/fyler/.next/server/pages/_document.js:267:19)
    at loadGetInitialProps (/srv/fyler/fyler/node_modules/next/dist/next-server/lib/utils.js:5:101)

Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot read property 'indexOf' of null
    at /srv/fyler/fyler/node_modules/rc-menu/lib/MenuItem.js:254:30
    at new Connect(MenuItem) (/srv/fyler/fyler/node_modules/mini-store/cjs/connect.js:64:33)
    at d (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
    at bb (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/srv/fyler/fyler/node_modules/next/dist/next-server/server/render.js:53:851)
    at Function.getInitialProps (/srv/fyler/fyler/.next/server/pages/_document.js:267:19)
    at loadGetInitialProps (/srv/fyler/fyler/node_modules/next/dist/next-server/lib/utils.js:5:101)

Error occurred prerendering page "/login". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot read property 'indexOf' of null
    at /srv/fyler/fyler/node_modules/rc-menu/lib/MenuItem.js:254:30
    at new Connect(MenuItem) (/srv/fyler/fyler/node_modules/mini-store/cjs/connect.js:64:33)
    at d (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
    at bb (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/srv/fyler/fyler/node_modules/next/dist/next-server/server/render.js:53:851)
    at Function.getInitialProps (/srv/fyler/fyler/.next/server/pages/_document.js:267:19)
    at loadGetInitialProps (/srv/fyler/fyler/node_modules/next/dist/next-server/lib/utils.js:5:101)
[   =] info  - Generating static pages (3/4)
Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot read property 'indexOf' of null
    at /srv/fyler/fyler/node_modules/rc-menu/lib/MenuItem.js:254:30
    at new Connect(MenuItem) (/srv/fyler/fyler/node_modules/mini-store/cjs/connect.js:64:33)
    at d (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
    at bb (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/srv/fyler/fyler/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/srv/fyler/fyler/node_modules/next/dist/next-server/server/render.js:53:851)
    at Function.getInitialProps (/srv/fyler/fyler/.next/server/pages/_document.js:267:19)
    at loadGetInitialProps (/srv/fyler/fyler/node_modules/next/dist/next-server/lib/utils.js:5:101)
info  - Generating static pages (4/4)

> Build error occurred
Error: Export encountered errors on following paths:
	/
	/404
	/login
	/register
    at exportApp (/srv/fyler/fyler/node_modules/next/dist/export/index.js:30:1103)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /srv/fyler/fyler/node_modules/next/dist/build/index.js:39:69
    at async /srv/fyler/fyler/node_modules/next/dist/build/tracer.js:1:525
npm ERR! code 1
npm ERR! path /srv/fyler/fyler
npm ERR! command failed
npm ERR! command sh -c next build

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/fyler/.npm/_logs/2020-12-29T19_46_55_430Z-debug.log
```

- OS: Debian 10.7
- Node.js: `12.20.0` and `15.5.0`

**Comment by ToolReaz** [comment]
Fixed. Thanks for the report !

Notice that this project is at its early stages. There is probably other bugs and not working features.
